# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GifMaker < Formula
  desc "A CLI tool for converting video files to GIFs"
  homepage "https://github.com/Akashdeep-Patra/gif-maker"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Akashdeep-Patra/gif-maker/releases/download/v0.0.5/gif-maker_Darwin_x86_64.tar.gz"
      sha256 "2574d9adc80ac1a689e56c2af45f970503142aa5c3a59c8fdb4a2caf342b71f0"

      def install
        bin.install "gif-maker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Akashdeep-Patra/gif-maker/releases/download/v0.0.5/gif-maker_Darwin_arm64.tar.gz"
      sha256 "1417fe3cdd43c64afeddea997ca971c9b4521178d325cdd5328764bc013e0e6f"

      def install
        bin.install "gif-maker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Akashdeep-Patra/gif-maker/releases/download/v0.0.5/gif-maker_Linux_x86_64.tar.gz"
      sha256 "0f1f953c6cb4147669b13e6f8a761f6444421dbee48e361a562d1106042100c2"
      def install
        bin.install "gif-maker"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Akashdeep-Patra/gif-maker/releases/download/v0.0.5/gif-maker_Linux_arm64.tar.gz"
      sha256 "1a081e2f2cacb690180848295cc95784fffe5c98a7af099271c7faa4f79a0008"
      def install
        bin.install "gif-maker"
      end
    end
  end
end
