# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zgv < Formula
  desc "A modern TUI Git client for Zed IDE"
  homepage "https://github.com/Akashdeep-Patra/zed-git-view"
  version "0.1.6"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Akashdeep-Patra/zed-git-view/releases/download/v0.1.6/zgv_0.1.6_darwin_x86_64.tar.gz"
      sha256 "d06b89051130fd5fad440b6b312ddde9c221dd89939b5bbf5a9d7e89ebeeaec9"

      def install
        bin.install "zgv"

        bash_completion.install "completions/zgv.bash" => "zgv"
        zsh_completion.install "completions/zgv.zsh" => "_zgv"
        fish_completion.install "completions/zgv.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Akashdeep-Patra/zed-git-view/releases/download/v0.1.6/zgv_0.1.6_darwin_aarch64.tar.gz"
      sha256 "9887f86e94f0ba2314fd2fc2561b9469ea80fc92ab0a6d3c639fc2c27d7f0946"

      def install
        bin.install "zgv"

        bash_completion.install "completions/zgv.bash" => "zgv"
        zsh_completion.install "completions/zgv.zsh" => "_zgv"
        fish_completion.install "completions/zgv.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Akashdeep-Patra/zed-git-view/releases/download/v0.1.6/zgv_0.1.6_linux_x86_64.tar.gz"
      sha256 "0a23c7bd4ec0edd087126a881dd55900ee349b79a40c7a6f58b350e778fb6672"
      def install
        bin.install "zgv"

        bash_completion.install "completions/zgv.bash" => "zgv"
        zsh_completion.install "completions/zgv.zsh" => "_zgv"
        fish_completion.install "completions/zgv.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Akashdeep-Patra/zed-git-view/releases/download/v0.1.6/zgv_0.1.6_linux_aarch64.tar.gz"
      sha256 "7f18e807fc54418b92c738dfff1a4a82d224a3e001b67dcaa16bf33790a876c5"
      def install
        bin.install "zgv"

        bash_completion.install "completions/zgv.bash" => "zgv"
        zsh_completion.install "completions/zgv.zsh" => "_zgv"
        fish_completion.install "completions/zgv.fish"
      end
    end
  end

  def caveats
    <<~EOS
      Shell completions have been installed.

      To use zgv inside Zed IDE, open the integrated terminal and run:
        zgv
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zgv version")
  end
end
