# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zgv < Formula
  desc "A modern TUI Git client for Zed IDE"
  homepage "https://github.com/Akashdeep-Patra/zed-git-view"
  version "0.1.8"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Akashdeep-Patra/zed-git-view/releases/download/v0.1.8/zgv_0.1.8_darwin_x86_64.tar.gz"
      sha256 "1dff57053382f49dcce305b6dfabde7715bde93e4064d4af0b8684118258804a"

      def install
        bin.install "zgv"

        bash_completion.install "completions/zgv.bash" => "zgv"
        zsh_completion.install "completions/zgv.zsh" => "_zgv"
        fish_completion.install "completions/zgv.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Akashdeep-Patra/zed-git-view/releases/download/v0.1.8/zgv_0.1.8_darwin_aarch64.tar.gz"
      sha256 "5c712412b847ee54fbf06af0d858ed5ad5432aea952295a59681463a793fd9e5"

      def install
        bin.install "zgv"

        bash_completion.install "completions/zgv.bash" => "zgv"
        zsh_completion.install "completions/zgv.zsh" => "_zgv"
        fish_completion.install "completions/zgv.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Akashdeep-Patra/zed-git-view/releases/download/v0.1.8/zgv_0.1.8_linux_x86_64.tar.gz"
      sha256 "7eb4c25f7c2d6c7f3f25df83bd0f56fd5f66f6d406fba5fa664d3f3b6d338108"
      def install
        bin.install "zgv"

        bash_completion.install "completions/zgv.bash" => "zgv"
        zsh_completion.install "completions/zgv.zsh" => "_zgv"
        fish_completion.install "completions/zgv.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Akashdeep-Patra/zed-git-view/releases/download/v0.1.8/zgv_0.1.8_linux_aarch64.tar.gz"
      sha256 "a1661b2944653e00245bb2ba2e6369dd393054d44d395160fe2e0da835a9d074"
      def install
        bin.install "zgv"

        bash_completion.install "completions/zgv.bash" => "zgv"
        zsh_completion.install "completions/zgv.zsh" => "_zgv"
        fish_completion.install "completions/zgv.fish"
      end
    end
  end

  def caveats
    <<~EOS
      Shell completions have been installed.

      To enable global Zed integration tasks:
        zgv zed install
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zgv version")
  end
end
