# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zgv < Formula
  desc "A modern TUI Git client for Zed IDE"
  homepage "https://github.com/Akashdeep-Patra/zed-git-view"
  version "0.1.9"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Akashdeep-Patra/zed-git-view/releases/download/v0.1.9/zgv_0.1.9_darwin_x86_64.tar.gz"
      sha256 "a2cb21bde42ca1ecdef1f06e48d789f48521ba93ee6fe6dec5657fe6b1764fb8"

      def install
        bin.install "zgv"

        bash_completion.install "completions/zgv.bash" => "zgv"
        zsh_completion.install "completions/zgv.zsh" => "_zgv"
        fish_completion.install "completions/zgv.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Akashdeep-Patra/zed-git-view/releases/download/v0.1.9/zgv_0.1.9_darwin_aarch64.tar.gz"
      sha256 "ee990cfac532833c5189f676a7e4828fed4f19e7f5e7bda0a870a9ec51991347"

      def install
        bin.install "zgv"

        bash_completion.install "completions/zgv.bash" => "zgv"
        zsh_completion.install "completions/zgv.zsh" => "_zgv"
        fish_completion.install "completions/zgv.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Akashdeep-Patra/zed-git-view/releases/download/v0.1.9/zgv_0.1.9_linux_x86_64.tar.gz"
      sha256 "2c2e2176ee152fb5917b577bbf1029f4204dd2c0e4be6bede9101ceab97ad548"
      def install
        bin.install "zgv"

        bash_completion.install "completions/zgv.bash" => "zgv"
        zsh_completion.install "completions/zgv.zsh" => "_zgv"
        fish_completion.install "completions/zgv.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Akashdeep-Patra/zed-git-view/releases/download/v0.1.9/zgv_0.1.9_linux_aarch64.tar.gz"
      sha256 "a7ac5b54b6baa7027ee1d05b3292fee4954973603813e570197c0ee3a8611666"
      def install
        bin.install "zgv"

        bash_completion.install "completions/zgv.bash" => "zgv"
        zsh_completion.install "completions/zgv.zsh" => "_zgv"
        fish_completion.install "completions/zgv.fish"
      end
    end
  end

  def caveats
    <<~EOS
      Shell completions have been installed.

      To enable global Zed integration tasks:
        zgv zed install
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zgv version")
  end
end
